gokul/Models/customer.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace gokul.Models
{
    public class customer
    {
        [Key]
        public int CustomerId { get; set; }
        public string? Name { get; set; }
        public int Age { get; set; }
        public string? FromAddress { get; set; }
        public string? ToAddress { get; set; }
        public string? City { get; set; }
        public int Weight { get; set; }

        [ForeignKey("Order")]
        public int OrderTypeId { get; set; }
        public order? Order { get; set; }
    }
}

gokul/Controllers/customerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using gokul.Data;
using gokul.Models;

namespace gokul.Controllers
{
    public class customerController : Controller
    {
        private readonly gokulContext _context;

        public customerController(gokulContext context)
        {
            _context = context;
        }

        // GET: customer
        public async Task<IActionResult> Index()
        {
            var gokulContext = _context.customer.Include(c => c.Order);
            return View(await gokulContext.ToListAsync());
        }

        // GET: customer/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.customer == null)
            {
                return NotFound();
            }

            var customer = await _context.customer
                .Include(c => c.Order)
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: customer/Create
        public IActionResult Create()
        {
            ViewData["OrderTypeId"] = new SelectList(_context.Set<order>(), "OrderTypeId", "OrderTypeId");
            return View();
        }

        // POST: customer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerId,Name,Age,FromAddress,ToAddress,City,Weight,OrderTypeId")] customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderTypeId"] = new SelectList(_context.Set<order>(), "OrderTypeId", "OrderTypeId", customer.OrderTypeId);
            return View(customer);
        }

        // GET: customer/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.customer == null)
            {
                return NotFound();
            }

            var customer = await _context.customer.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            ViewData["OrderTypeId"] = new SelectList(_context.Set<order>(), "OrderTypeId", "OrderTypeId", customer.OrderTypeId);
            return View(customer);
        }

        // POST: customer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CustomerId,Name,Age,FromAddress,ToAddress,City,Weight,OrderTypeId")] customer customer)
        {
            if (id != customer.CustomerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!customerExists(customer.CustomerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderTypeId"] = new SelectList(_context.Set<order>(), "OrderTypeId", "OrderTypeId", customer.OrderTypeId);
            return View(customer);
        }

        // GET: customer/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.customer == null)
            {
                return NotFound();
            }

            var customer = await _context.customer
                .Include(c => c.Order)
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: customer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.customer == null)
            {
                return Problem("Entity set 'gokulContext.customer'  is null.");
            }
            var customer = await _context.customer.FindAsync(id);
            if (customer != null)
            {
                _context.customer.Remove(customer);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool customerExists(int id)
        {
          return (_context.customer?.Any(e => e.CustomerId == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> detail1()

        {
            return View("Details");
        }
    
}
}

gokul/Controllers/executivesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using gokul.Data;
using gokul.Models;

namespace gokul.Controllers
{
    public class executivesController : Controller
    {
        private readonly gokulContext _context;

        public executivesController(gokulContext context)
        {
            _context = context;
        }

        // GET: executives
        public async Task<IActionResult> Index()
        {
            var gokulContext = _context.executive.Include(e => e.Order);
            return View(await gokulContext.ToListAsync());
        }

        // GET: executives/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.executive == null)
            {
                return NotFound();
            }

            var executive = await _context.executive
                .Include(e => e.Order)
                .FirstOrDefaultAsync(m => m.ExecutiveId == id);
            if (executive == null)
            {
                return NotFound();
            }

            return View(executive);
        }

        // GET: executives/Create
        public IActionResult Create()
        {
            ViewData["OrderTypeId"] = new SelectList(_context.Set<order>(), "OrderTypeId", "OrderTypeId");
            return View();
        }

        // POST: executives/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ExecutiveId,ExecutiveName,Age,OrderTypeId,PhnNo")] executive executive)
        {
            if (ModelState.IsValid)
            {
                _context.Add(executive);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderTypeId"] = new SelectList(_context.Set<order>(), "OrderTypeId", "OrderTypeId", executive.OrderTypeId);
            return View(executive);
        }

        // GET: executives/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.executive == null)
            {
                return NotFound();
            }

            var executive = await _context.executive.FindAsync(id);
            if (executive == null)
            {
                return NotFound();
            }
            ViewData["OrderTypeId"] = new SelectList(_context.Set<order>(), "OrderTypeId", "OrderTypeId", executive.OrderTypeId);
            return View(executive);
        }

        // POST: executives/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ExecutiveId,ExecutiveName,Age,OrderTypeId,PhnNo")] executive executive)
        {
            if (id != executive.ExecutiveId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(executive);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!executiveExists(executive.ExecutiveId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderTypeId"] = new SelectList(_context.Set<order>(), "OrderTypeId", "OrderTypeId", executive.OrderTypeId);
            return View(executive);
        }

        // GET: executives/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.executive == null)
            {
                return NotFound();
            }

            var executive = await _context.executive
                .Include(e => e.Order)
                .FirstOrDefaultAsync(m => m.ExecutiveId == id);
            if (executive == null)
            {
                return NotFound();
            }

            return View(executive);
        }

        // POST: executives/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.executive == null)
            {
                return Problem("Entity set 'gokulContext.executive'  is null.");
            }
            var executive = await _context.executive.FindAsync(id);
            if (executive != null)
            {
                _context.executive.Remove(executive);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool executiveExists(int id)
        {
            return (_context.executive?.Any(e => e.ExecutiveId == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> acceptorder()

        {
            return View("acceptorder");
        }
    }
}

gokul/Views/customer/Create.cshtml
@model gokul.Models.customer

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-white">Create</h1>

<h4 class="text-white">customer</h4>
<hr />
<div class="row">
    <div class="col-md-4 text-white">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FromAddress" class="control-label"></label>
                <input asp-for="FromAddress" class="form-control" />
                <span asp-validation-for="FromAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ToAddress" class="control-label"></label>
                <input asp-for="ToAddress" class="form-control" />
                <span asp-validation-for="ToAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div> Select your order type <br /> 1.Glass <br /> 2. Furnitures <br /> 3.Envelop <br /> 4.Medicals <br /> 5.Electronics <br /> 6.Food Items <br />
            </div>
            <div class="form-group">
                <label asp-for="OrderTypeId" class="control-label"></label>
                <select asp-for="OrderTypeId" class ="form-control" asp-items="ViewBag.OrderTypeId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="text-white" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

gokul/Views/customer/Delete.cshtml
@model gokul.Models.customer

@{
    ViewData["Title"] = "Delete";
}

<h1 class="text-white">Decline</h1>

<h3 class="text-white">Are you sure you want to delete this order?</h3>
<div>
    <h4 class="text-white">customer</h4>
    <hr />
    <dl class="row text-white">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FromAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FromAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ToAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ToAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Order)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Order.OrderTypeId)
        </dd>
    </dl>
    
    <form class="text-white" asp-action="Delete">
        <input class="text-white" type="hidden" asp-for="CustomerId" />
        <input  type="submit" value="Decline" class="btn btn-danger" /> |
     @*   <a class="text-white" asp-action="Index">Back to List</a>*@
    </form>
</div>

gokul/Views/customer/Details.cshtml
@model gokul.Models.customer

@{
    ViewData["Title"] = "Details";
}

<h1 class="text-white">Details</h1>

<div>
    <h4 class="text-white">customer</h4>
    <hr />
    <dl class="row text-white">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FromAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FromAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ToAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ToAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Order)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Order.OrderTypeId)
        </dd>
    </dl>
</div>
<div>
 @*   <a class="text-white" asp-action="Edit" asp-route-id="@Model?.CustomerId">Edit</a> |
    <a class="text-white" asp-action="Index">Back to List</a>*@
</div>

gokul/Views/customer/Edit.cshtml
@model gokul.Models.customer

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-white">Edit</h1>

<h4 class="text-white">customer</h4>
<hr />
<div class="row text-white">
    <div class="col-md-4 text-white">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CustomerId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FromAddress" class="control-label"></label>
                <input asp-for="FromAddress" class="form-control" />
                <span asp-validation-for="FromAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ToAddress" class="control-label"></label>
                <input asp-for="ToAddress" class="form-control" />
                <span asp-validation-for="ToAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderTypeId" class="control-label"></label>
                <select asp-for="OrderTypeId" class="form-control" asp-items="ViewBag.OrderTypeId"></select>
                <span asp-validation-for="OrderTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="text-white"  asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

gokul/Views/customer/Index.cshtml
@model IEnumerable<gokul.Models.customer>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-white">Index</h1>

<p class="text-white">
    <a class="text-white"  asp-action="Create">Create New</a>
</p>
<table class="table text-white">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FromAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ToAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FromAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ToAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Weight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Order.OrderTypeId)
          @*  </td>
            <td> 
                   <div class="panel-heading">
                 <div class="btn-group pull-right">

                    @*<a class="nav-link text-dark text-white" asp-area="" asp-controller="executives" asp-action="acceptorder">accept</a>*@


                      @*      <a class="text-white btn btn-success" asp-area="" asp-controller="customer" asp-action="detail1" asp-route-id="@item.CustomerId">Accept</a>
                       <a href="#" class="btn btn-primary" onclick="this.disabled=true">Decline</a>
                  </div>
                   </div> </td>*@
            
            <td>
               <div class="panel-heading">
                   <div class="btn-group pull-right">
                <a class="text-white btn btn-success" asp-action="Details" asp-route-id="@item.CustomerId">Accept</a> 
                <a class="text-white btn btn-primary" asp-action="Delete" asp-route-id="@item.CustomerId">Decline</a>
                  @*  <a asp-action="acceptorder" asp-route-id="@item.CustomerId">accept</a>*@
                  </div>

</div>                
            </td>
        </tr>
}
    </tbody>
</table>

gokul/Views/customer/custview.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2></h2>